### PR TITLE
Add message for requesting steps to reproduce

### PR DESCRIPTION
**Pull request by violine1101**
I found that this message which I saw other mods/helpers use would be useful to have handy but it's not in the message application yet. I changed it a bit to make it a bit more succinct and similarly formatted to the other AR messages.

### CODE REVIEW

**Comment by Greymagic27** [comment]
Could rename from 'steps' to 'repro' ? Since that's what the instructions are asking for

**Comment by violine1101** [comment]
Yeah, good idea, that's easier to type too. Will change

**Comment by Greymagic27** [comment]
My current message is this:

"Please update the description to include steps to reproduce this issue, as well as expected VS observed results.

Please also attach any needed commands, datapacks, resourcepacks, screenshots, videos or worlds needed to help reproduce this issue."

I wonder if something could be added with regards to the second line and attaching any datapacks, videos, worlds, etc that are needed

**Comment by violine1101** [comment]
Yeah that'd probably be useful - changed!

I've also adjusted the final line to sound a bit less aggressive.

**Pull request merged**
