### PR TITLE
Enable copy shortcut

### LINKED ISSUE #43: Copy message when press <enter> in text field.
Basically should behave same as if the Copy button is pressed. Saves step of switching between keyboard and mouse.

### PR DESCRIPTION
**Pull request by SPGoding**
Resolve #43.

### CODE REVIEW

**Comment by Marcono1234** [comment]
This seems to work, but it also triggers when pressing `ENTER` to select a value from the message or project dropdown when navigating using the keyboard. However, maybe that is acceptable?

**Comment by SPGoding** [comment]
Actually it won't be triggered if you press Enter on these drop boxes (at least on my machine).

**Comment by Marcono1234** [comment]
Hmm, for me on Firefox it is triggered. I am using https://marcono1234.github.io/helper-messages/#MC for testing it.

Note that you have to select a message which does not require additional input, e.g. "Account issue". Otherwise it will just make the input box shake because it is missing input.

**Comment by SPGoding** [comment]
Yeah, it's different between Chromium and Firefox. Though I suppose both behaviors are acceptable?

**Comment by SPGoding** [comment]
I just changed the key to Ctrl + C. It should be good now as it doesn't conflict with anything

**Comment by NeunEinser** [comment]
I would prefer enter, as that's the key I would assume.
Also, I sometimes copy the issue key from the textfield to the jira link thing, after having pasted the message, and I'm not sure which Ctrl + C action would take preference here.

**Comment by SPGoding** [comment]
Okay, the final solution: pressing Ctrl + C anywhere (unless you highlighted some texts on the webpage) OR pressing Enter in the text input can copy the message.

**Pull request merged**
