### PR TITLE
Add keys for messages in messages.json

### PR DESCRIPTION
**Pull request by SPGoding**
This PR adds keys for messages in `messages.json`, making it possible for arisa to locate messages by using keys like `duplicate`.

### CODE REVIEW

**Comment by NeunEinser** [comment]
How is that change related to Arisa?

**Comment by Pokechu22** [comment]
Presumably the goal would be to make arisa directly use the messages in this repo instead of having its own copy of the messages.

**Comment by SPGoding** [comment]
Merge into #34

**Comment by Marcono1234** [comment]
@SPGoding can this branch be deleted, or do you want to keep it?

**Comment by SPGoding** [comment]
Yeah it can be deleted. Thanks for reminding!

**Pull request closed without merging**
